# Default minimal task configuration for emCore library
# This provides only essential system monitoring when no user configuration is provided
# Users should create their own tasks.yaml file for their application

tasks:
  - name: "WatchdogMonitor"
    function: "task_watchdog_monitor"
    priority: "high"
    period_ms: 500
    enabled: true
    description: "Essential watchdog and system monitoring task"
    StackSize: 2048
    CreateNative: true

# This is a minimal fallback configuration
# For real applications, create your own tasks.yaml file with your application tasks
# Priority levels: idle, low, normal, high, critical
# period_ms: 0 means run once, >0 means periodic task
# enabled: true/false to enable/disable task at startup
# StackSize: Stack size in bytes for native RTOS tasks
# CreateNative: true = native RTOS task, false = cooperative task
